### ISSUE TITLE
Crash when configuring some FOMODs

### ISSUE THREAD

**Issue by Nucleartaxi** [cyberrumor/ammo#10]
I'm getting a crash when configuring some FOMOD installers, including ruins clutter improved and underground. It crashes immediately upon running `configure #`. 

```
  File "/home/test/Documents/repos/source/ammo/ammo/./ammo.py", line 76, in <module>
    sys.exit(ui.repl())
  File "/home/test/Documents/repos/source/ammo/ammo/ui.py", line 376, in repl
    if not (ret := command["func"](*args)):
  File "/home/test/Documents/repos/source/ammo/ammo/ui.py", line 105, in configure
    steps = self.controller._fomod_install_steps(fomod_installer_root_node)
  File "/home/test/Documents/repos/source/ammo/ammo/controller.py", line 378, in _fomod_install_steps
    plug_dict["description"] = plugin.find("description").text.strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by cyberrumor** [comment]
I wasn't able to reproduce but I pushed what I think should fix your issue. Can you try pulling the latest update and retest?

**Comment by Nucleartaxi** [comment]
I pulled the latest update, but it still crashes when attempting to configure the underground textures mod, same error. I deleted and reinstalled the mod as well before testing.

**Comment by cyberrumor** [comment]
Dang, alright. Let me get to a point where I can reproduce this then I'll get it fixed. Is this the mod that's crashing for you? https://www.nexusmods.com/skyrimspecialedition/mods/14365

**Comment by Nucleartaxi** [comment]
Yeah

**Comment by cyberrumor** [comment]
I was able to reproduce with that mod and pushed a fix up. Let me know if that works for you!

**Comment by cyberrumor** [comment]
Closing for lack of activity, as I'm pretty sure this is resolved now. Please feel free to open another issue if you still experience this, or if you find any other bugs. Thanks for reporting!
